name: wikipedia
description: Wikipedia API client and models for dartpedia.
version: 0.1.0
publish_to: none
resolution: workspace

environment:
  sdk: ^3.5.0

dependencies:
  http: ^1.3.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0